version: "3.9"  # optional since v1.27.0

services:
  database:
    image: postgres:13.1
    container_name: bmx-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpw
      - POSTGRES_DB=devdb
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data


  mongodb:
    image: mongo
    container_name: bmx-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpw
      - POSTGRES_DB=devdb
    volumes:
      - ./mongodb-data/:/data/db
